### PR TITLE
Feat/purchase order nft

### LINKED ISSUE #524: [Purchase Orders] - Purchase order NFT smart contract
User story: 

I need to be able to submit the details of my purchase order

* Setup purchase order NFT smart contract 

  * Should record amount in stable coin

  * Should record type of item being purchased

  * Should record exporter

  * Should record the delivery address

  * Should record the terms of payment

  * Should record the shipping route

  * Should record items and price per item

### PR DESCRIPTION
**Pull request by Aman-zishan**
### Pull-Request Checklist

- [X] Code is up-to-date with the `main` branch
- [X] `yarn lint` passes with this change
- [X] `yarn clarinet:check` passes with this change
- [X] `yarn clarinet:tests` passes with this 
- [X] `yarn unit-tests` passes with this
- [X] Run `yarn eol`
- [X] Run `yarn format`
- [X] Run `yarn cleanup`
- [X] This pull request links relevant issues as `Fixes #524`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [X] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by Aman-zishan** [comment]
@dorucioclea NFT metadata example [here](ipfs://bafybeidntmydwppanpzvvz4clnp5ngbsyd6vd2aheppbnsuogh442s3kyu/)

**Comment by dorucioclea** [comment]
I see there are a lot of changes. Does your formatting use tabs or spaces? I'll have a look on the NFT contract shortly 😁 thank you

**Comment by Aman-zishan** [comment]
> I see there are a lot of changes. Does your formatting use tabs or spaces? I'll have a look on the NFT contract shortly 😁 thank you

Yes, I think my global prettier settings are overriding, the current one. Do you have any recommendation to fix that.

**Comment by Aman-zishan** [comment]
merge depends on #525

**Comment by dorucioclea** [comment]
@dependabot rebase

**Pull request merged**
